name: automated-tests

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install pip -U; python -m pip install poetry; poetry install
    - name: Run tests
      run: |
        poetry run coverage run --source kafka_schema_registry_admin -m pytest --verbose
        poetry run coverage report -m
